blank_issues_enabled: false
contact_links:
  - name: 问题咨询
    url: https://github.com/NXY666/JsjiamiV6-Decryptor/discussions/new?category=%E9%97%AE%E9%A2%98%E5%92%A8%E8%AF%A2
    about: 解密器不会使用、代码细节咨询等在此提问。为了提升效率，请完整阅读 README.md 后再提问。